### PR TITLE
Add support for EBPF_CLS_JMP32 JIT and interpret

### PR DESCRIPTION
**Pull request by Alan-Jowett**
Add support for EBPF_CLS_JMP32 x64 JIT and interpret

Resolves: #29 

Signed-off-by: Alan Jowett <alanjo@microsoft.com>

### CODE REVIEW

**Comment by Alan-Jowett** [comment]
Need to add ARM64 JIT for the new instruction class.

**Comment by Alan-Jowett** [comment]
@qmonnet I am finally fixing this. uBPF is still missing the atomic store operations though.

**Review by matt-gretton-dann — CHANGES_REQUESTED** [review]
OK apart from what looks like two stray commits in the CI loop.

**Review by matt-gretton-dann — APPROVED** [review]
LGTM.

**Pull request merged**
