### PR TITLE
Fix a couple minor issues with the test infrastructure.

### PR DESCRIPTION
**Pull request by lsgunth**
Ran into a couple bugs:

1) The testdata.py script crashes with a RuntimeError on Python3.8 and above
2) The requirements.txt is out of date with the requirements

### CODE REVIEW

**Comment by lsgunth** [comment]
Added a commit to this PR to support python3 in expand_testcase.

**Comment by pchaigno** [comment]
Thanks for the pull request @lsgunth!

Could you extend Travis CI's test matrix to test Python 3.8 or higher as well?

**Comment by lsgunth** [comment]
Hmm, that doesn't seem easy to do. 

To use Travis's built-in python version matrix we have to use "language: python" which I don't think we can do without removing "language: cpp".

The alternative would be to find a python3.8 backport ppa for Xenial and install it manually. This seems like it might be a bit fragile to me.

Using the latest dist in travis (Bionic) only gets us up to python 3.6; but loses python 3.5.

I'm not really sure if it's really worth the effort as it's largely just test framework stuff that uses python and not critical to work for users of this library, only developers who can afford to solve a few bugs if they crop up.

**Comment by jpsamaroo** [comment]
Alternatively, maybe we should move ubpf to a more capable CI platform? GitHub Actions and GitLab are both free (to my knowledge), while SourceHut is paid but also is highly configurable and allows essentially unlimited CI.

**Comment by lsgunth** [comment]
Github actions is pretty similar to travis. They have the same quirks.

However, github actions does have various libraries to help. So we could probably rely on 

https://github.com/actions/setup-python

To install whatever version of python without having to handle python version installs ourselves.

**Comment by pchaigno** [comment]
> The alternative would be to find a python3.8 backport ppa for Xenial and install it manually. This seems like it might be a bit fragile to me.
Using the latest dist in travis (Bionic) only gets us up to python 3.6; but loses python 3.5.
I'm not really sure if it's really worth the effort as it's largely just test framework stuff that uses python and not critical to work for users of this library, only developers who can afford to solve a few bugs if they crop up.

I agree :+1: A better long term solution to test different Python versions would be to move to GitHub actions.

Could you rebase on top of https://github.com/iovisor/ubpf/pull/56, which fixed the Travis CI builds?

**Review by pchaigno — APPROVED** [review]

**Comment by lsgunth** [comment]
Done. I had to drop the first commit seeing it was the same issue fixed in 9f9d0512896992ecbb4d11c6c870acc0f99f943f and 64bda8f1b6e35d36f62442c6ec50d46ef344bd85.

**Review by pchaigno — APPROVED** [review]

**Comment by pchaigno** [comment]
Thanks!

**Pull request merged**
